# Generated by Django 5.0.1 on 2024-02-20 04:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Funding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=24, verbose_name="제목")),
                ("content", models.TextField(max_length=1000, verbose_name="내용")),
                ("goal_price", models.IntegerField(default=0, verbose_name="목표금액")),
                ("total_price", models.IntegerField(default=0, verbose_name="받은금액")),
                (
                    "photo",
                    models.ImageField(
                        blank=True, upload_to="fundings/%Y%m%d", verbose_name="이미지"
                    ),
                ),
                (
                    "present_link",
                    models.CharField(max_length=1000, verbose_name="상품 링크"),
                ),
                (
                    "is_closed",
                    models.BooleanField(
                        blank=True, default=False, verbose_name="펀딩 종료"
                    ),
                ),
                (
                    "is_achieved",
                    models.BooleanField(
                        blank=True, default=False, verbose_name="펀딩 달성 여부"
                    ),
                ),
                ("msg_count", models.IntegerField(default=0, verbose_name="메시지 개수")),
                (
                    "created_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="작성일"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Funding_Msg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "comment_name",
                    models.CharField(max_length=8, verbose_name="친구에게 보여질 이름"),
                ),
                (
                    "funding_price",
                    models.IntegerField(default=0, null=True, verbose_name="선물금액"),
                ),
                ("content", models.TextField(verbose_name="축하 메시지")),
                (
                    "written_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="메시지 작성일"),
                ),
            ],
        ),
    ]
