# Generated by Django 5.0.1 on 2024-01-30 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='작성일')),
                ('title', models.CharField(max_length=24, verbose_name='제목')),
                ('content', models.TextField(max_length=1000, verbose_name='내용')),
                ('goal_price', models.IntegerField(default=0, verbose_name='목표금액')),
                ('funding_price', models.IntegerField(default=0, null=True, verbose_name='받은금액')),
                ('photo', models.ImageField(blank=True, upload_to='posts/%Y%m%d', verbose_name='이미지')),
                ('present_link', models.CharField(max_length=100, verbose_name='상품 링크')),
            ],
        ),
        migrations.CreateModel(
            name='Funding_Msg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
    ]
