# Generated by Django 5.0.1 on 2024-02-16 07:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fundings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="funding",
            name="present_link",
            field=models.CharField(max_length=250, verbose_name="상품 링크"),
        ),
    ]
