# Generated by Django 5.0.1 on 2024-02-19 13:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fundings", "0002_alter_funding_present_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="funding",
            name="present_link",
            field=models.CharField(max_length=1000, verbose_name="상품 링크"),
        ),
        migrations.AlterField(
            model_name="funding_msg",
            name="comment_name",
            field=models.CharField(max_length=8, verbose_name="친구에게 보여질 이름"),
        ),
    ]
