# Generated by Django 5.0.1 on 2024-02-01 02:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fundings", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="funding",
            name="is_closed",
            field=models.BooleanField(blank=True, default=False, verbose_name="펀딩 종료"),
        ),
        migrations.AlterField(
            model_name="funding",
            name="total_price",
            field=models.IntegerField(default=0, verbose_name="받은금액"),
        ),
    ]
