# Generated by Django 5.0.1 on 2024-02-05 15:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="name",
        ),
        migrations.AlterField(
            model_name="user",
            name="nickname",
            field=models.CharField(
                blank=True, max_length=24, null=True, unique=True, verbose_name="닉네임"
            ),
        ),
    ]
